### ISSUE TITLE
#4.2 Black Box Testing

### ISSUE THREAD

**Issue by jihoonieeee** [Charlenelzq/INF2001_P8-4#13]
Task: Select ONE of the prominent methods related to your use cases and design the decision table black box testing for it. Provide a short description on how you designed your black box testing for the method and what are the test cases
Goal: Complete black box testing section
Completion Criteria: Detailed explanation for black box testing section

**Comment by ProxyLeech** [comment]
**Chosen Use Case**: Create Job Assigment (UC-1)

The "Create Job Assignment (UC-1)" use case has multiple input fields (Date, Time, Route, Number of Staff Required), each with valid and invalid states. 

1. High Priority
2. Complexity of Scenarios: Multiple alternative scenarios and validation checks
3. Decision-Driven Scenarios: Many decisions are based on user input and conditions (e.g., checking if the date is within the allocation week, verifying the required number of staff)

**Chosen Testing Method**: Equivalence Partitioning combined with Decision Table Testing

Equivalence Partitioning allows us to reduce the number of test cases by categorizing inputs into "equivalent" groups. Each partition is expected to yield similar behavior, making it possible to test representative values instead of every possible input.

1. Information may be missing (e.g., date, route, number of staff).
2. Date and time may not be within valid ranges.
3. There may be constraints on staff availability.

**Comment by ProxyLeech** [comment]
**Black Box Testing Updates:**

Chosen Use Case: Create Job Assignment (UC-1)
Testing Method: Black Box Testing using Decision Table Testing instead of Equivalence Partitioning.

Updated Testing Approach - Focus on Decision Table Testing

Decision Table Testing exclusively to cover possible combinations of inputs and outputs.
Evaluate each input condition separately with binary outcomes (Y or N) for simplification.

**Defined Input Conditions:**
C1: Valid date (within 1-week scheduling period)
C2: Valid time (within working hours: 08:00–21:00)
C3: Valid route (route exists in the system)
C4: Valid staff allocation (within available limit)

**Test Combinations:**
16 total combinations were initially considered, but reduced to 5 after eliminating redundant tests based on the conditions affecting job creation outcomes.


**Test Scenarios and Expected Outcomes:**
Invalid Creation:
Invalid Date: Date outside 1-week range → Expect error "Invalid Date."
Invalid Time: Time outside 08:00–21:00 range → Expect error "Invalid Time."
Invalid Route: Route not defined in the system → Expect error "Invalid Route."
Staff Exceeds Limit: Staff allocation exceeds limit → Expect error "Invalid Staff Count."

**Valid Creation:**
All inputs valid → Job creation succeeds.


**Test Case Table (Summary):**
Document detailed scenarios based on the reduced decision table.

**Each test case includes:**
Pre-Conditions: Describe specific conditions required for each test.
Test Data: Specific data values for date, time, route, and staff.
Test Steps: Step-by-step instructions for each scenario.
Expected Results: Match expected outcomes to specified errors or success messages.

High Priority: Ensuring accurate job assignment creation with minimal redundancy.
Complexity: Focused on decision-driven scenarios with clear outcomes per condition.
